// Code generated by "stringer -type=Shape -trimprefix=Shape"; DO NOT EDIT.

package gamedata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShapeCircle-0]
	_ = x[ShapeSquare-1]
	_ = x[ShapeTriangle-2]
	_ = x[ShapeHexagon-3]
	_ = x[ShapeStar-4]
	_ = x[ShapeCross-5]
	_ = x[ShapeBonus-6]
}

const _Shape_name = "CircleSquareTriangleHexagonStarCrossBonus"

var _Shape_index = [...]uint8{0, 6, 12, 20, 27, 31, 36, 41}

func (i Shape) String() string {
	if i < 0 || i >= Shape(len(_Shape_index)-1) {
		return "Shape(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Shape_name[_Shape_index[i]:_Shape_index[i+1]]
}
